name: Performance Benchmark

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run benchmarks
        run: |
          python -m pytest tests/test_performance.py \
            --benchmark-json=benchmark.json
      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: performance-benchmark
          path: benchmark.json